declare const WEBPACK_DEFINED_API_URL_BASE: string;
export const API_URL_BASE = WEBPACK_DEFINED_API_URL_BASE;

declare const WEBPACK_DEFINED_BROWSER_URL_BASENAME: string;
export const BROWSER_URL_BASENAME = WEBPACK_DEFINED_BROWSER_URL_BASENAME;
